org.gradle.jvmargs=-Xmx768m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.workers.max=1

kotlin.code.style=official

android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=false

haven.coverage.enforce=false
haven.piececid.verify.enabled=true
